name: Build palera1n

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-binpack:
    needs: build-loader
    runs-on: macos-latest
    steps:
      - name: Cache Procursus
        uses: actions/cache@v3
        id: procache  
        with:
          path: |
            ~/__cache
          key: ${{ runner.os }}-procursus

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout Procursus
        if: steps.binpack_cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: ProcursusTeam/Procursus
          path: src/Procursus

      - name: Setup Procursus Bootstrap (install)
        if: steps.procache.outputs.cache-hit != 'true'
        run: |
          wget https://apt.procurs.us/bootstraps/big_sur/bootstrap-darwin-amd64.tar.zst
          sudo gtar --preserve-permissions -xkf ./bootstrap-darwin-amd64.tar.zst -C /
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
          PATH=/opt/procursus/sbin:/opt/procursus/bin:$PATH sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt -V full-upgrade -y || :
          sudo /opt/procursus/bin/apt install asciidoc autoconf autoconf-archive automake autopoint bash bison cmake docbook-xml docbook-xsl fakeroot findutils flex file gawk git gnupg gpgrt-tools groff gzip ldid libtool libltdl-dev llvm make ncurses-bin openssl patch pkg-config po4a python3 sed tar triehash wget xz-utils zstd -y

      - name: Add Procursus to PATH
        run: |
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH

      - name: Setup Procursus Bootstrap (cache)
        if: steps.procache.outputs.cache-hit == 'true'
        run: |
          sudo mkdir -p ~/__cache/procursus/var/cache/apt/archives/partial ~/__cache/procursus/var/lib/apt/lists/partial
          sudo rsync -aP ~/__cache/procursus /opt
          sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt --allow-downgrades -V dist-upgrade -y
          sudo /opt/procursus/bin/apt --allow-downgrades -V dist-upgrade -y

      - name: Build binpack.tar
        run: |
          rm -rf Makefile
          curl -L0 https://raw.githubusercontent.com/ProcursusTeam/Procursus/main/Makefile
          gmake MEMO_CFVER=1800 MEMO_TARGET=iphoneos-arm64 binpack

      - name: Copy Procursus to Cache Location
        run: |
          sudo mkdir -p ~/__cache
          sudo rsync -aP /opt/procursus ~/__cache
          sudo rm -rf ~/__cache/procursus/var/cache/apt/archives/partial ~/__cache/procursus/var/lib/apt/lists/partial ~/__cache/procursus/Library/dpkg/triggers/Lock
