name: Build palera1n

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-binpack:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout Procursus
        uses: actions/checkout@v3
        with:
          repository: ProcursusTeam/Procursus
          path: src/Procursus

      - name: Setup Procursus Bootstrap (install)
        run: |
          wget https://apt.procurs.us/bootstraps/big_sur/bootstrap-darwin-amd64.tar.zst
          sudo gtar --preserve-permissions -xkf ./bootstrap-darwin-amd64.tar.zst -C /
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
          PATH=/opt/procursus/sbin:/opt/procursus/bin:$PATH sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt -V full-upgrade -y || :
          sudo /opt/procursus/bin/apt install asciidoc autoconf autoconf-archive automake autopoint bash bison cmake docbook-xml docbook-xsl fakeroot findutils flex file gawk git gnupg gpgrt-tools groff gzip ldid libtool libltdl-dev llvm make ncurses-bin openssl patch pkg-config po4a python3 sed tar triehash wget xz-utils zstd -y

      - name: Add Procursus to PATH
        run: |
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH

      - name: Build binpack.tar
        run: |
          rm -rf Makefile
          curl -L0 https://raw.githubusercontent.com/ProcursusTeam/Procursus/main/Makefile
          gmake MEMO_CFVER=1800 MEMO_TARGET=iphoneos-arm64 binpack

